### ISSUE TITLE
Environment template - "magic" replacer

### ISSUE THREAD

**Issue by filfreire** [tranquility-bdd/tranquility-bdd#16]
An environment will allow to persist temporarily  data before and after Actions, and it'll be read during actions.

For a  simple initial approach we can do the following:

1) act like a global key value map and let the "users" set values to it or get values and apply their own transformations

2) have a method to also read a string and find and replace in a copy of that string with all the `{{variables}}` the environment holds.  This may be useful in Actions's `setup` method - since `setup` wouldn't have to worry about getting keys - searching on a string, creating a new string - similarly to how in other similar software the user doesn't have to worry about this.

**In this ticket** let's worry about "magic replacement" - so point **2)**

**Comment by jmromanos** [comment]
I think that we can close this issue now as it's already implemented.

**Comment by filfreire** [comment]
@jmromanos you're right, we can close it.
