### ISSUE TITLE
Setup publishing of package to a "mavenrepo" like repository for golang

### ISSUE THREAD

**Issue by filfreire** [tranquility-bdd/tranquility-bdd#17]
Let's setup publishing of package to a "mavenrepo" like repository for golang. It can be done after issue #13

**Comment by jmromanos** [comment]
To publish the library package  we only need to make the repo public.

**Comment by filfreire** [comment]
@jmromanos we can close this one, but let's just add an example on README of how to import the repo, like the example file you had the other day making an experimental request.
