### ISSUE TITLE
Add package documentation to GoDoc

### ISSUE THREAD

**Issue by jmromanos** [tranquility-bdd/tranquility-bdd#20]
The documentation will be avaliable in GoDoc after #17. The documentation of the package should be written following the [godoc guidelines](https://blog.golang.org/godoc-documenting-go-code) so it can be correctly generated.

**Comment by jmromanos** [comment]
As the repository is public the documentation is public and can be accessed [here](https://godoc.org/github.com/tranquility-bdd/tranquility). We just need to improve it 🙂 .

**Comment by filfreire** [comment]
@jmromanos let's close this issue after pr #29
