### ISSUE TITLE
Action template - integrate with Environment "magic" replacer

### ISSUE THREAD

**Issue by filfreire** [tranquility-bdd/tranquility-bdd#27]
This issue is a follow-up to issue #16.

We need to, as pre-setup work of the actual `Action.Run` phase:
- pre-transform every internal variable of Action using the "magic" replacer.

Example:
I define the url of the Action as:
```
{{hostname}}/user/{{userId}}
```
Both `{{hostname}}` and `{{userId}}` need to be replaced before running the actual HTTP request.

The same applies for any found `{{tag}}` in the body, headers and params of the HTTP request setup.

/cc @jmromanos

**Comment by jmromanos** [comment]
If we could use {{.hostname}} it could be really helpful as we could use [template package](https://golang.org/pkg/text/template/) from the standard library.

**Comment by filfreire** [comment]
@jmromanos seems promising, sure!

**Comment by jmromanos** [comment]
We need to define what happens if the variable is not found in the Environment. We could replace with "<no value>", that's the default option,  a zero value or throw an error

**Comment by filfreire** [comment]
@jmromanos we should throw an error right there and then.

**Comment by filfreire** [comment]
@jmromanos closing this one after PR #35
