### ISSUE TITLE
Replacement of Headers might be wrongly defined

### ISSUE THREAD

**Issue by filfreire** [tranquility-bdd/tranquility-bdd#34]
The way we're replacing each header, might be wrong:
https://github.com/tranquility-bdd/tranquility/blob/d8a2fd8f0c58f8f942071388197c780e4f1cb541/action.go#L54

1. Keys of Headers are not supposed to be parsed by the environment, only the values of Headers - that needs to be changed.
2. Would the `Add` replace the existing Header?

/cc @jmromanos

**Comment by jmromanos** [comment]
1. Ok, that can be easily changed
2. Header is a map, so Add will only replace a header if it existed before

**Comment by filfreire** [comment]
solved in pr #36
