### ISSUE TITLE
Create Collection template - set of Requests

### ISSUE THREAD

**Issue by jmromanos** [tranquility-bdd/tranquility-bdd#46]
We should create a Collection template, just a simple collection of Requests to be executed in order. We should create this in my opinion for the following reasons:

- Automatically run all users requests without having to call run each time.
- Possible potentional to do parallel executions in the future
- Method to import a Postman collection

**Comment by filfreire** [comment]
@jmromanos the last point
> - Method to import a Postman collection

we should keep for a separate ticket and decide how best we're going to implement it.

**Comment by jmromanos** [comment]
We can still discuss all Postman related topics in #44

**Comment by filfreire** [comment]
@jmromanos closing this one since PR #47 was merged
